# Generated by Django 5.0.3 on 2024-04-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0006_alter_location_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
