# Generated by Django 5.0.3 on 2024-05-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0010_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('relation_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=60)),
                ('answer_text', models.TextField()),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
