# Generated by Django 5.0.3 on 2024-05-31 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0016_alter_extrafields_privacy_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTemporal.place'),
        ),
    ]
