# Generated by Django 5.0.3 on 2024-04-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0005_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
    ]
