# Generated by Django 5.0.3 on 2024-05-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0013_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Normal'), (2, 'Difficult')], default=1),
        ),
    ]
