# Generated by Django 5.0.3 on 2024-06-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0018_remove_question_difficulty_difficultquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafields',
            name='highscore',
            field=models.IntegerField(default=0),
        ),
    ]
