# Generated by Django 5.0.3 on 2024-06-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0025_alter_extrafields_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficultquestion',
            name='max_points',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='difficultquestion',
            name='medium_points',
            field=models.SmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='difficultquestion',
            name='min_points',
            field=models.SmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='easyquestion',
            name='max_points',
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='easyquestion',
            name='medium_points',
            field=models.SmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='easyquestion',
            name='min_points',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='normalquestion',
            name='max_points',
            field=models.SmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='normalquestion',
            name='medium_points',
            field=models.SmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='normalquestion',
            name='min_points',
            field=models.SmallIntegerField(default=10),
        ),
    ]
