# Generated by Django 5.0.3 on 2024-06-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0027_extrafields_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='profile_picture',
            field=models.URLField(default='http://127.0.0.1:8000/static/img/profilePictures/def.jpg'),
        ),
    ]
