# Generated by Django 5.0.3 on 2024-05-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0009_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
