# Generated by Django 5.0.3 on 2024-05-31 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0012_rename_relation_id_place_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.DateField()),
                ('place_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appTemporal.place')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('text', models.TextField()),
                ('pub_date', models.DateField()),
                ('question_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appTemporal.question')),
            ],
        ),
    ]
