# Generated by Django 5.0.3 on 2024-06-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0019_extrafields_highscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafields',
            name='highscore',
        ),
    ]
