# Generated by Django 5.0.3 on 2024-06-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0021_extrafields_about_extrafields_highscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='about',
            field=models.TextField(default='This is my bio! I love animals and history'),
        ),
    ]
