# Generated by Django 5.0.3 on 2024-06-03 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0022_alter_extrafields_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafields',
            name='about',
        ),
    ]
