# Generated by Django 5.0.3 on 2024-06-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0024_extrafields_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafields',
            name='about',
            field=models.TextField(default='This is my bio! I love animals and history', max_length=60),
        ),
    ]
