# Generated by Django 5.0.3 on 2024-04-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTemporal', '0003_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
